//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAudioApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyAudioTB
    {
        public int Id { get; set; }
        public string AlbumName { get; set; }
        public string Song { get; set; }
        public string AlbumBy { get; set; }
        public string Label { get; set; }
        public string Filename { get; set; }
    }
}
